# Programs to install with `brew install`
- vim
- git
- git-lfs
- the_silver_searcher
- readline
- gnupg
- tree
- --HEAD universal-ctags/universal-ctags/universal-ctags
- evince
- most
- diff-so-fancy

